version: "3.1"
services:

  nginx:
    image: nginx:1.14
    container_name: nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./Nginx/core:/etc/nginx/conf.d
        - ./public:/var/www/
        - ./Nginx/Logs:/var/log/nginx/
      #  - ./Nginx/html:/usr/share/nginx/html/
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./public:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    # restart: always
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
