version: "3.1"
services:

  nginx:
    image: tutum/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx.log:/var/log/access
      - ./logs/nginx.log:/var/log/error

  # portainer:
  #   image: portainer/portainer:demo
  #   container_name: "portainer-app"
  #   command: --no-analytics
  #   networks:
  #     - local
  #   volumes:
  #     - /tmp/manager_run/docker.sock:/var/run/docker.sock

  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./public:/public

  db:
    image: mysql:5.6
    restart: always
    environment:
      DB_HOST: 'php-fpm'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    # depends_on:
    #   - mysql